PACKAGE_VERSION="25.06"
PACKAGE_NAME="8500-leds"
MAKE[0]="make module"
CLEAN="make clean"
BUILT_MODULE_NAME[0]="8500_leds"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net"
AUTOINSTALL="yes"
NO_WEAK_MODULES="yes"
